#!/usr/bin/python3
print('Content-Type: text/html')
print()
print('''
<!doctype html>
<html>
    <head>
        <title>Hello World</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h2>Hello World, CGI!</h2>
    </body>
</html>
''')
