#!/usr/bin/python3
from mcrcon import MCRcon
print('Content-Type: text/html')
print()
print('''
<!doctype html>
<html>
    <head>
        <title>Hello World</title>
        <meta charset="utf-8">
    </head>
    <body>
''')
with MCRcon("0.0.0.0", "minecraft") as mcr:
    resp = mcr.command("/whitelist add bob")
    print("<h3>%s</h3>\n" % resp)
print('''
        <h2>Hello World, CGI!</h2>
    </body>
</html>
''')
