#!/usr/bin/python3
from mcrcon import MCRcon
import requests
import cgi
import os


def mc_connect(ip, password):
    mcr = MCRcon(ip, password)
    mcr.connect()
    resp = mcr.command("/whitelist add bob")
    print('<h3 align="center">Minecraft控制台</h3>')
    print('<div>'+resp+'</div>')
    mcr.disconnect()

    '''print(\'''
        <form method="POST">
            <div align="center">
                <div align="center">
                    <textarea name="comment" id="comment" readonly = true rows = "50" cols = "100" style="resize:none;"></textarea>
                </div>
                <input type="text" name="hometown" id="hometown" size="22" />
            </div>
        </form>
        <div align="center">
            <input type="submit" onClick="doMagic();">
        </div>
    \''')'''


def log():
    print('''
        <script type="text/javascript">
            function add(){
                var now = new Date();
                var div = document.getElementById('scrolldIV');
                div.innerHTML = div.innerHTML + '<br>';
                div.scrollTop = div.scrollHeight;
            }
            var test = document.getElementById("scrolldIV");
            test.onchange = add;
        </script>
        <div align="left" id="scrolldIV" style="overflow:auto; height: 100%; width: 100%; border: 1px solid;">
            <table>
                <script language="javascript" type="text/javascript">
                    var timeout = setInterval(reloadChat, 1000);    
                    function reloadChat () {
    ''')
    fo = open("/mcserver/logs/latest.log", "rb")
    global start_point
    start_point = 0
    fo.seek(start_point, 1)
    for line in fo.readlines():
        print("$('#scrolldIV').html(%s+'<br>')" % str(line.decode()))
    start_point = fo.tell()
    fo.close()

    print('''
                }
            </script>
        </table>
    </div> 
    ''')


def get_token():
    sum = 'sdfkjeiqwijdij38489feiwj3r89udvjis4htih8vys804hdsh8y8ehw3r893987544651454+46565-8487215ekhgeuihouoawuhdhahoiwhd9pwhegqhwdnjsklallq'
    url = 'http://flask-test:5000/get_token/'+sum
    r = requests.get(url)
    if r.status_code == requests.codes.ok:
        return (r.text)
    else:
        return 'Error'


def login(token):
    if token != '' or token != None:
        pass
        #---------html & javascript----------#


def java_script():
    print('''
<script
    src="https://code.jquery.com/jquery-3.6.0.slim.js"
    integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY="
    crossorigin="anonymous">
</script>
<script>
function doMagic(){  
    var homeTown = document.getElementById("hometown").value;  
    document.getElementById("comment").value = document.getElementById("comment").value + homeTown+"\\n";
    document.getElementById("hometown").value="";
}
</script>
''')


#-----------#
print("Content-type:text/html")
print()                             # 空行，告诉服务器结束头部
print('<html>')
print('<head>')
print('<meta charset="utf-8">')
#print('<meta http-equiv=Refresh Content=3>')
print('<title>Minecraft控制台</title>')
java_script()
print('</head>')
print('<body>')

# form = cgi.FieldStorage()
# if form.getvalue('comment'):
#    command = form.getvalue('comment')
#    print("<div>%s</div>" % command)

token = get_token()
print("<div>%s</div>" % token)
mc_connect('mc-test', 'minecraft')
log()
print("<input type = button value = 登出 onclick =\"location.href='http://0.0.0.0/logout'\">")
print('</body>')
print('</html>')
